name: JSDoc Convention Check

on:
  push:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run JSDoc convention check
        run: npm run jsdoc:check
