name: JSDoc Action Patch

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Document
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate JSDoc documentation
        uses: zhennann/jsdoc-action@v1.2.1
        with:
          source_dir: ./assets/scripts
          recurse: true
          output_dir: ./assets/scripts/documentation

