name: Generate JSDocs Documentation

on:
  push:
jobs:
  jsdocs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./assets/scripts
          output_dir: ./jsdocs
          template: minami
          front_page: README.md
      - name: Commit Docs
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: noreply@github.com
          message: 'Generated JSDocs'
          add: 'jsdocs/*'
