name: Compress Images
on:
  pull_request:
    paths:
      - "**.jpg"
      - "**.jpeg"
      - "**.png"
      - "**.webp"
      - "**.gif"
  workflow_dispatch:
jobs:
  build:
    name: Compress Images
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Compress Regular Images Using Calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Optimize Images (lossless)
        uses: Doist/optimize-images-action@v2
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Optimize images (lossless)"
